ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
ERROR:pymodbus.client.sync:[Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:41 - INFO - This is an info message
2023-12-01 18:46:41 - WARNING - This is a warning message
2023-12-01 18:46:41 - ERROR - This is an error message
2023-12-01 18:46:41 - CRITICAL - This is a critical message
2023-12-01 18:46:51 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:51 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:52 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:53 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:54 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:55 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:46:56 - ERROR - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2023-12-01 18:54:27 - INFO - This is an info message
2023-12-01 18:54:27 - WARNING - This is a warning message
2023-12-01 18:54:27 - ERROR - This is an error message
2023-12-01 18:54:27 - CRITICAL - This is a critical message
2023-12-01 18:57:15 - INFO - This is an info message
2023-12-01 18:57:15 - INFO - This is an info message
2023-12-01 18:57:15 - WARNING - This is a warning message
2023-12-01 18:57:15 - WARNING - This is a warning message
2023-12-01 18:57:15 - ERROR - This is an error message
2023-12-01 18:57:15 - ERROR - This is an error message
2023-12-01 18:57:15 - CRITICAL - This is a critical message
2023-12-01 18:57:15 - CRITICAL - This is a critical message
2023-12-02 09:12:07 - INFO - This is an info message
2023-12-02 09:12:07 - INFO - This is an info message
2023-12-02 09:12:07 - WARNING - This is a warning message
2023-12-02 09:12:07 - WARNING - This is a warning message
2023-12-02 09:12:07 - ERROR - This is an error message
2023-12-02 09:12:07 - ERROR - This is an error message
2023-12-02 09:12:07 - CRITICAL - This is a critical message
2023-12-02 09:12:07 - CRITICAL - This is a critical message
2023-12-02 11:31:55 - INFO - This is an info message
2023-12-02 11:31:55 - INFO - This is an info message
2023-12-02 11:31:55 - WARNING - This is a warning message
2023-12-02 11:31:55 - WARNING - This is a warning message
2023-12-02 11:31:55 - ERROR - This is an error message
2023-12-02 11:31:55 - ERROR - This is an error message
2023-12-02 11:31:55 - CRITICAL - This is a critical message
2023-12-02 11:31:55 - CRITICAL - This is a critical message
2023-12-02 12:06:14 - INFO - This is an info message
2023-12-02 12:06:14 - INFO - This is an info message
2023-12-02 12:06:14 - WARNING - This is a warning message
2023-12-02 12:06:14 - WARNING - This is a warning message
2023-12-02 12:06:14 - ERROR - This is an error message
2023-12-02 12:06:14 - ERROR - This is an error message
2023-12-02 12:06:14 - CRITICAL - This is a critical message
2023-12-02 12:06:14 - CRITICAL - This is a critical message
2023-12-02 15:07:55 - INFO - This is an info message
2023-12-02 15:07:55 - INFO - This is an info message
2023-12-02 15:07:55 - WARNING - This is a warning message
2023-12-02 15:07:55 - WARNING - This is a warning message
2023-12-02 15:07:55 - ERROR - This is an error message
2023-12-02 15:07:55 - ERROR - This is an error message
2023-12-02 15:07:55 - CRITICAL - This is a critical message
2023-12-02 15:07:55 - CRITICAL - This is a critical message
2023-12-04 09:24:59 - INFO - This is an info message
2023-12-04 09:24:59 - INFO - This is an info message
2023-12-04 09:24:59 - WARNING - This is a warning message
2023-12-04 09:24:59 - WARNING - This is a warning message
2023-12-04 09:24:59 - ERROR - This is an error message
2023-12-04 09:24:59 - ERROR - This is an error message
2023-12-04 09:24:59 - CRITICAL - This is a critical message
2023-12-04 09:24:59 - CRITICAL - This is a critical message
2023-12-04 09:29:46 - INFO - This is an info message
2023-12-04 09:29:46 - INFO - This is an info message
2023-12-04 09:29:46 - WARNING - This is a warning message
2023-12-04 09:29:46 - WARNING - This is a warning message
2023-12-04 09:29:46 - ERROR - This is an error message
2023-12-04 09:29:46 - ERROR - This is an error message
2023-12-04 09:29:46 - CRITICAL - This is a critical message
2023-12-04 09:29:46 - CRITICAL - This is a critical message
